### ISSUE TITLE
NsfwSpy.App Incompatibility with Node.js v18.6.0+ / v16.17.0+

### ISSUE THREAD

**Issue by Todokete** [NsfwSpy/NsfwSpy.NET#12]
When attempting to build the NsfwSpy web app when using v18.6.0+ / v16.17.0+ of Node.js, it will throw out a "ERR_LOADER_CHAIN_INCOMPLETE" error and get stuck trying to run 'npm install' on loop. Node.js v16.16.0 works perfectly fine due to "ERR_LOADER_CHAIN_INCOMPLETE" not existing as an error in previous versions.

**Comment by d00ML0rDz** [comment]
I've just tried updating the npm packages we use in the NsfwSpy.App project. Mind pulling from master to get the latest changes and see if that has fixed it?

**Comment by d00ML0rDz** [comment]
You may need to run `npm install` in the client-app directory to install the latest package changes.
