### ISSUE TITLE
Classify multiple images , best way to remove lamda? 

### ISSUE THREAD

**Issue by FitzM** [NsfwSpy/NsfwSpy.NET#14]
I've used NsfwSpy successfully on a few test files , I'm now trying to set it up where the classification is written to a Dictionary. 

Based on the results I want to run a function that moves the file into a corresponding directory based on the classification. 

The issue I'm having currently is because I don't want to mess with the nuget package, all the images in a directory and classified and then the Dictionary is ready and files are moved.  But if there is an error during classification the program crashes and the sorting function isn't used. 

Question is , what is the best way to break up the lamda function so that I can sort files based on the classification? It will make it quiet a bit faster too so I can sort each file as it's classified instead of writing the entire list , then reading the entire list to sort.

**Comment by d00ML0rDz** [comment]
Hi, thanks for reporting the issue 😊

Do you have any example code of what you are currently doing, so I can try and understand what you are trying to achieve?

**Comment by d00ML0rDz** [comment]
I think something like this should do what you need:

```
            var directory = @"D:\Images";
            var nsfwSpy = new NsfwSpy();

            var files = Directory.GetFiles(directory).Where((file) =>
            {
                var extension = Path.GetExtension(file).ToLower();
                return extension == ".jpg" || extension == ".jpeg" || extension == ".png";
            });

            if (files.Count() > 0)
            {
                nsfwSpy.ClassifyImages(files, (filePath, result) =>
                {
                    var label = result.PredictedLabel;
                    var filename = Path.GetFileName(filePath);
                    var folder = Path.GetDirectoryName(filePath);
                    var newDirectory = Path.Combine(folder, label);

                    if (!Directory.Exists(newDirectory))
                        Directory.CreateDirectory(newDirectory);

                    var newPath = Path.Combine(newDirectory, filename);
                    if (!File.Exists(newPath))
                        File.Move(filePath, newPath);

                    Console.WriteLine($"{filename} => {newPath}");
                });
            }
```
